//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 14 17:07:03 GMT-10:00 2007
//----------------------------------------------------

package edu.gatech.constraints.cassowary;

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */
    public static final int MINUS = 6;
    public static final int DIVIDE = 9;
    public static final int UMINUS = 7;
    public static final int NUMBER = 12;
    public static final int VARIABLE = 13;
    public static final int EOF = 0;
    public static final int PLUS = 5;
    public static final int EQ = 4;
    public static final int error = 1;
    public static final int RPAREN = 11;
    public static final int TIMES = 8;
    public static final int LPAREN = 10;
    public static final int GEQ = 2;
    public static final int LEQ = 3;
}
